// Copyright 2021 bilibili. All rights reserved. Author: Guo, Weiji guoweiji@bilibili.com
// 哔哩哔哩版权所有 2021。作者：郭伟基 guoweiji@bilibili.com
//
// This file is generated by make_table.go.
// Base point pre computation
// --------------------------
//
// This table has 4 * 63 elements, starting with the following:
// index | bits    | point
// ------+---------+------------------------------
//     1 | 0 0 0 0 0 1 | [1]G
//     2 | 0 0 0 0 1 0 | [2^40]G
// ...
//    63 | 1 1 1 1 1 1 | [2^200 + 2^160 + 2^120 + 2^80 + 2^40 + 1]G
// followed by a copy of this with each element multiplied by 2^10, and then
// by 2^20, 2^30
//

package internal

//const sm2PrecomputedBaseMultiples fiat.SM2Element[4][63][2] = {{{{}}}}
